"""WAF / CDN / Proxy detection — passive fingerprinting (wafw00f-inspired).

Detects edge protection from evidence the target already returns: response
headers, body markers of challenge pages, and cookie names. No active probing
(no fake attack payloads — that is exploit-adjacent and out of CASA's scope).

Why it matters: a WAF in front of the target changes how findings should be
interpreted (mitigation in depth) and enriches the attack surface map.
"""
from __future__ import annotations

import re
from typing import Any

from agent.core.context import AssessmentContext
from agent.core.finding import make_finding, make_fingerprint
from agent.core.interfaces import AssessmentModule

# name -> (header regex map, body regexes, cookie-name regexes)
# Curated from public signature sets (wafw00f / fingerprinting write-ups).
WAF_SIGNATURES: dict[str, dict[str, list[tuple[str, str]]]] = {
    "Cloudflare": {
        "headers": [
            ("server", r"cloudflare"),
            ("cf-ray", r".+"),
            ("cf-cache-status", r".+"),
        ],
        "cookies": ["__cfduid", "__cf_bm", "cf_chl"],
        "body": [("challenge page", r"Attention Required!|cf-browser-verification|jschl")],
    },
    "AWS WAF / CloudFront": {
        "headers": [
            ("server", r"CloudFront"),
            ("x-amz-cf-id", r".+"),
            ("x-amzn-requestid", r".+"),
        ],
        "body": [("block page", r"ERROR: The request could not be satisfied")],
    },
    "Akamai": {
        "headers": [
            ("server", r"AkamaiGHost|Akamai"),
            ("x-akamai-transformed", r".+"),
        ],
        "cookies": ["akamai"],
        "body": [("reference error", r"Access Denied.*Reference #|You don't have permission to access")],
    },
    "Imperva / Incapsula": {
        "headers": [("x-iinfo", r".+"), ("x-cdn", r"Imperva")],
        "cookies": ["incap_ses", "visid_incap", "reese84"],
        "body": [("block page", r"Request unsuccessful. Incapsula incident ID")],
    },
    "Sucuri": {
        "headers": [
            ("server", r"Sucuri/Cloudproxy"),
            ("x-sucuri-id", r".+"),
            ("x-sucuri-cache", r".+"),
        ],
        "cookies": ["sucuri_cloudproxy_uuid"],
    },
    "F5 BIG-IP / ASM": {
        "headers": [
            ("server", r"BigIP|BIG-IP|F5"),
            ("x-wa-info", r".+"),
        ],
        "cookies": ["TS[a-zA-Z0-9]{6}", "MRHSession"],
        "body": [("support id", r"The requested URL was rejected.*Support ID")],
    },
    "ModSecurity": {
        "headers": [("server", r"Mod_Security|mod_security")],
        "body": [("block page", r"Not Acceptable!.*mod_security|This error was generated by Mod_Security")],
    },
    "Barracuda": {
        "headers": [("server", r"Barracuda"), ("x-barracuda", r".+")],
        "cookies": ["barb"],
    },
    "Citrix NetScaler": {
        "headers": [("via", r"NS-CACHE"), ("server", r"NS-CACHE|NetScaler")],
        "cookies": ["ns_af", "citrix_ns_id"],
    },
    "Fastly": {
        "headers": [
            ("x-served-by", r"cache-"),
            ("x-cache", r".+"),
            ("via", r"varnish|fastly"),
        ],
    },
    "KeyCDN": {"headers": [("server", r"KeyCDN"), ("x-cache", r".+")]},
    "StackPath / MaxCDN": {
        "headers": [("server", r"NetDNA|StackPath|stackpath")],
    },
    "Squarespace": {"headers": [("x-contextid", r".+"), ("via", r"squarespace")]},
    "Vercel": {"headers": [("server", r"Vercel"), ("x-vercel-id", r".+")]},
    "Netlify": {"headers": [("server", r"Netlify"), ("x-nf-request-id", r".+")]},
}

CDN_HINTS: dict[str, list[tuple[str, str]]] = {
    "server": [(r"cloudflare", "Cloudflare"), (r"cloudfront", "AWS CloudFront")],
    "x-cache": [(r"miss|hit", "Generic CDN cache")],
}


class WafDetectModule(AssessmentModule):
    name = "waf_detect"
    phase = "WAF_DETECT"
    critical = False

    def __init__(self, validator) -> None:
        self._validator = validator

    async def run(self, ctx: AssessmentContext) -> None:
        root = ctx.raw_results.get("http_root")
        if not root:
            return

        headers = {k.lower(): v for k, v in (root.get("headers") or {}).items()}
        body = root.get("body", "") or ""
        cookies = root.get("cookies") or []
        cookie_blob = " ".join(
            c.get("name", "") if isinstance(c, dict) else str(c) for c in cookies
        )

        detected: list[dict[str, Any]] = []

        for waf_name, sig in WAF_SIGNATURES.items():
            evidence: list[dict[str, Any]] = []
            for header_name, pattern in sig.get("headers", []):
                value = headers.get(header_name, "")
                if value and re.search(pattern, value, re.IGNORECASE):
                    evidence.append(
                        {
                            "type": "http_header",
                            "header": header_name,
                            "value": value[:200],
                            "note": f"matches {waf_name} header signature",
                        }
                    )
            for cname in sig.get("cookies", []):
                # Cookie signature: the literal name IS the pattern — match it
                # against the names of cookies the target actually set.
                if re.search(cname, cookie_blob, re.IGNORECASE):
                    evidence.append(
                        {
                            "type": "cookie_name",
                            "cookie": cname,
                            "note": f"cookie name matches {waf_name} signature",
                        }
                    )
            for label, pattern in sig.get("body", []):
                if re.search(pattern, body, re.IGNORECASE):
                    evidence.append(
                        {
                            "type": "body_marker",
                            "marker": label,
                            "note": f"body content matches {waf_name} block/challenge page",
                        }
                    )
            if evidence:
                detected.append({"name": waf_name, "evidence": evidence, "kind": "waf/cdn"})

        # Generic CDN hints (informational only, kept separate from WAF verdicts)
        for header_name, hints in CDN_HINTS.items():
            value = headers.get(header_name, "")
            if not value:
                continue
            for pattern, label in hints:
                if label.startswith("Generic"):
                    continue
                if re.search(pattern, value, re.IGNORECASE) and label not in [
                    d["name"] for d in detected
                ]:
                    detected.append(
                        {
                            "name": label,
                            "kind": "cdn",
                            "evidence": [
                                {
                                    "type": "http_header",
                                    "header": header_name,
                                    "value": value[:200],
                                    "note": "weak CDN indicator",
                                }
                            ],
                        }
                    )

        ctx.raw_results["waf"] = {
            "detected": [d["name"] for d in detected],
            "kinds": {d["name"]: d["kind"] for d in detected},
            "detail": detected,
        }

        if detected:
            names = ", ".join(d["name"] for d in detected)
            is_cdn_only = all(d["kind"] == "cdn" for d in detected)
            f = make_finding(
                title=f"Edge protection detected: {names}",
                category="TECHNOLOGY",
                severity="INFO",
                confidence="HIGH" if not is_cdn_only else "MEDIUM",
                description=(
                    f"Passive fingerprinting indicates the target sits behind "
                    f"{names}. {'CDN layer' if is_cdn_only else 'WAF/CDN layer'} signatures were "
                    "matched in response headers, cookies or block-page markers."
                ),
                evidence=[{"type": "waf_detection", "matches": names, **{k: v for k, v in d.items() if k != "name"}} for d in detected],
                affected_asset=ctx.target_url,
                impact=(
                    "An edge protection layer filters some automated attacks before they "
                    "reach the application. WAFs are compensating controls, not fixes: "
                    "they do not remediate the underlying vulnerabilities in this report."
                ),
                remediation=(
                    "Keep the WAF/CDN rules current, but treat them as defense-in-depth: "
                    "fix root-cause findings in the application itself and avoid relying "
                    "solely on edge filtering."
                ),
                references=[
                    "https://owasp.org/www-community/Web_Application_Firewall",
                    "https://github.com/EnableSecurity/wafw00f",
                ],
                source=self.name,
            )
            f["fingerprint"] = make_fingerprint(self.name, ctx.base_domain, "waf")
            f["metadata"] = {"waf": [d["name"] for d in detected]}
            ctx.findings.append(f)
